import * as Blockly from 'blockly';
import { javascriptGenerator } from 'blockly/javascript';

type PinMap = Map<string, 'INPUT' | 'OUTPUT'>;

export interface ArduinoBuildResult {
  jsSource: string;
  loopBody: string;
  arduinoCode: string;
  pinModes: string[];
}

const toSafeLoopBody = (jsSource: string) => {
  let code = jsSource || '';
  code = code.replace(/\bvar\b/g, 'int');
  code = code.replace(/\blet\b/g, 'int');
  code = code.replace(/\bconst\b/g, 'int');
  code = code.replace(/__arduinoDigitalWrite\((\d+),\s*(HIGH|LOW)\);/g, 'digitalWrite($1, $2);');
  code = code.replace(/__arduinoDigitalRead\((\d+)\)/g, 'digitalRead($1)');
  code = code.replace(/__arduinoAnalogRead\("?(A[0-5])"?\)/g, 'analogRead($1)');
  code = code.replace(/__arduinoServoWrite\((\d+),\s*([^)]+)\);/g, 'servo_$1.write($2);');
  return code.trim();
};

const collectPinModes = (source: string) => {
  const modes: PinMap = new Map();
  const writePins = [...source.matchAll(/__arduinoDigitalWrite\((\d+),/g)].map((m) => m[1]);
  const readPins = [...source.matchAll(/__arduinoDigitalRead\((\d+)\)/g)].map((m) => m[1]);
  writePins.forEach((pin) => modes.set(pin, 'OUTPUT'));
  readPins.forEach((pin) => {
    if (!modes.has(pin)) modes.set(pin, 'INPUT');
  });
  return modes;
};

const collectServoPins = (source: string) =>
  Array.from(new Set([...source.matchAll(/__arduinoServoWrite\((\d+),/g)].map((m) => m[1])));

export function buildArduinoCodeFromWorkspace(workspace: Blockly.Workspace): ArduinoBuildResult {
  const jsSource = javascriptGenerator.workspaceToCode(workspace);
  const loopBody = toSafeLoopBody(jsSource);
  const pinModesMap = collectPinModes(jsSource);
  const servoPins = collectServoPins(jsSource);

  const pinModes = Array.from(pinModesMap.entries()).map(([pin, mode]) => `  pinMode(${pin}, ${mode});`);
  const servoDeclarations = servoPins.map((pin) => `Servo servo_${pin};`);
  const servoAttach = servoPins.map((pin) => `  servo_${pin}.attach(${pin});`);

  const arduinoCode = [
    '// Generated by STEMverse Blockly Arduino IDE',
    servoPins.length ? '#include <Servo.h>' : '',
    servoDeclarations.join('\n'),
    '',
    'void setup() {',
    ...pinModes,
    ...servoAttach,
    '}',
    '',
    'void loop() {',
    ...(loopBody ? loopBody.split('\n').map((line) => `  ${line}`) : ['  // Add blocks to generate logic']),
    '}',
    '',
  ]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return { jsSource, loopBody, arduinoCode, pinModes };
}

export function runMockArduinoSimulation(loopBody: string) {
  const logs: string[] = [];
  const pinState: Record<string, number> = {};
  const analogState: Record<string, number> = { A0: 321, A1: 512, A2: 128, A3: 892, A4: 444, A5: 777 };

  const api = {
    __arduinoDigitalWrite: (pin: number, value: 'HIGH' | 'LOW') => {
      pinState[String(pin)] = value === 'HIGH' ? 1 : 0;
      logs.push(`Pin ${pin}: ${value}`);
    },
    __arduinoDigitalRead: (pin: number) => {
      const v = pinState[String(pin)] ?? 0;
      logs.push(`Read D${pin}: ${v}`);
      return v;
    },
    __arduinoAnalogRead: (pin: string) => {
      const v = analogState[pin] ?? 0;
      logs.push(`Read ${pin}: ${v}`);
      return v;
    },
    __arduinoServoWrite: (pin: number, angle: number) => {
      const clamped = Math.max(0, Math.min(180, Number(angle) || 0));
      logs.push(`Servo ${pin}: ${clamped}deg`);
    },
    delay: (ms: number) => {
      logs.push(`Delay ${Number(ms) || 0}ms`);
    },
    digitalWrite: (pin: number, value: 'HIGH' | 'LOW') => {
      pinState[String(pin)] = value === 'HIGH' ? 1 : 0;
      logs.push(`Pin ${pin}: ${value}`);
    },
    digitalRead: (pin: number) => {
      const v = pinState[String(pin)] ?? 0;
      logs.push(`Read D${pin}: ${v}`);
      return v;
    },
    analogRead: (pin: string) => {
      const v = analogState[pin] ?? 0;
      logs.push(`Read ${pin}: ${v}`);
      return v;
    },
  };

  try {
    const runner = new Function(
      'api',
      `"use strict";
const __arduinoDigitalWrite = api.__arduinoDigitalWrite;
const __arduinoDigitalRead = api.__arduinoDigitalRead;
const __arduinoAnalogRead = api.__arduinoAnalogRead;
const __arduinoServoWrite = api.__arduinoServoWrite;
const delay = api.delay;
const digitalWrite = api.digitalWrite;
const digitalRead = api.digitalRead;
const analogRead = api.analogRead;
${loopBody}
`
    );
    runner(api);
    return {
      success: true,
      logs,
      pinState,
    };
  } catch (error) {
    return {
      success: false,
      logs: [...logs, `Simulation error: ${error instanceof Error ? error.message : 'Unknown'}`],
      pinState,
    };
  }
}
